### ISSUE TITLE
SeaChat Premium Plan Changes

### ISSUE THREAD

**Issue by amy17519** [seasalt-ai/wiki#263]
**1. Add a new page under _Payments_ that explains all the paid plan options**
The landing pages should be online on 8/1. If not, you can get the screenshots at https://chat-dev.seasalt.ai/

- the 4 plans
<img width="1138" alt="Screenshot 2024-08-01 at 00 07 53" src="https://github.com/user-attachments/assets/febc9e86-3e98-431a-99ac-d18ed60bab49">

- model pricing
<img width="944" alt="Screenshot 2024-08-01 at 00 08 09" src="https://github.com/user-attachments/assets/4111b36a-6804-401f-a302-45e3b7748ab4">

- support plan 
<img width="1077" alt="Screenshot 2024-08-01 at 00 08 31" src="https://github.com/user-attachments/assets/671d3d7d-f467-405b-b3a7-dcda6aa0ab63">

The page needs to have both screenshots and text explanation of the plans. You can use the following texts

### 中文文案

**免費試用**

* 終身 100 條免費文字回覆
* 1 個 AI 助理
* 知識庫包含最多 10 份文件（最大 200KB）和 20 萬詞元（tokens）
* 1 個管理員和 1 個工作區
* 每個AI助理回應費用 $0.01 美元
* 使用ChatGPT-3.5-turbo模型

**標準方案**

* 2 個 AI 助理
* 知識庫包含最多 100 份文件（最大 1 MB）和 100 萬詞元（tokens）
* 1 個管理員、1 個使用者成員和 1 個工作區
* 每個AI助理回應費用 $0.01 美元
* 使用ChatGPT-3.5-turbo模型

**高級方案**
* 10 個 AI 助理
* 知識庫包含最多 500 份文件（最大 10 MB）和 500 萬詞元（tokens）
* 1 個管理員、3 個使用者成員和 2 個工作區
* 每個AI助理回應費用 $0.006 美元起
* 可替換 LLM 模型，每個模型價格不一，請參考官網定價（包括GPT-4o mini, GPT-4o, GPT-4-turbo, ChatGPT-3.5-turbo, Mistral）
* 可添加電話語音助理（每分鐘起價 $0.15 美元）
* 進階功能：記憶 / API / 移除 SeaChat 品牌字樣 / 語音助理

### 英文文案

**Free**

* Lifetime 100 free AI text replies
* 1 AI Agent
* Knowledge base includes up to 10 documents (200KB max) and 200k tokens
* 1 owner account and 1 workspace
* Model: ChatGPT-3.5-turbo

**Standard**
* 2 AI Agents
* Knowledge base includes up to 100 documents (1 MB max) and 1 million tokens
* 1 owner account, 1 member account, and 1 workspace
* Every AI agent response costs $0.01USD
* Model: ChatGPT-3.5-turbo

**Premium**
* 10 AI Agents
* Knowledge base includes up to 500 documents (10 MB max) and 5 million tokens
* 1 owner account, 3 member account, and 2 workspace
* AI agent response starting price $0.006USD
* Choose your favorite model. Options include GPT-4o mini, GPT-4o, GPT-4-turbo, ChatGPT-3.5-turbo, Mistral etc. Please refer to SeaChat official website for pricing details
* Voice AI agent over phone calls (starting from $0.15 per minute)
* Advanced features : Memory / API Access / SeaChat branding Removal / Voice Agent

2. Label and clarify Premium features
- Agent Memory: https://wiki.seasalt.ai/seachat/seachat-manual/02-create-agent/03-advanced-settings/03-agent-memory/
- For each Knowledge page, clarify that each plan has different file upload limitation (redirect to `File Size Rule`)
- Workspace Management: clarify the number of seats allowed in each plan
- API Access: Clarify under SeaChat API page. API is only available for Premium and Enterprise plans 

3. Add a page (Page title: "File Size Rule") under _Knowledge_ that explains the file limitation of each premium plan
Free -  Knowledge base includes up to 10 documents (200KB max) and 200k tokens
Standard -  Knowledge base includes up to 100 documents (1 MB max) and 1 million tokens
Premium - Knowledge base includes up to 500 documents (10 MB max) and 5 million tokens

**Comment by xuchen** [comment]
wait, how are we writing about this? is it just copying from the landing page to wiki? or do we add more explanations? 

one thing I want is this: 

in the wiki, some features are "Premium" only, or "Standard" plan only, we should go to the wiki and explain whether a feature is a paid feature or not.
