### ISSUE TITLE
Re: [seasalt-ai/SeaX] SeaX <-> SeaChat conversation sync (Issue #3268)

### ISSUE THREAD

**Issue by itIsJim** [seasalt-ai/wiki#280]
- Add wiki: It should be under https://wiki.seasalt.ai/seax/seax_messaging/seax-agent-bulk-send/ with a section called "Conversation synchronized between SeaX and SeaChat".

**Comment by amy17519** [comment]
See https://github.com/seasalt-ai/SeaX/issues/3268#issuecomment-2286818021
